message("Found sdl2-config.cmake at " ${CMAKE_CURRENT_LIST_DIR})

if(MSVC)
	message("Finding SDL for Visual C++")
	set(SDL2_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")
	# Support both 32 and 64 bit builds
	if (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	  message("64 Bit SDL Found")
	  set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2_ttf.lib")
	else ()
	  message("32 Bit SDL Found")
	  set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2_ttf.lib")
	endif ()
else ()
	message("Finding SDL for GCC/MinGW")
	set(SDL2_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/x86_64-w64-mingw32/include/SDL2")
	set(SDL2_LIBDIR "${CMAKE_CURRENT_LIST_DIR}/x86_64-w64-mingw32/lib")
	set(SDL2_LIBRARIES "-L${SDL2_LIBDIR}  -lmingw32 -lSDL2main -lSDL2 -mwindows")
	SET(GCC_SDL2_COMPILER_FLAGS "-Wl,-Bstatic -lmingw32 -lSDL2main -lSDL2 -Wl,-Bdynamic -lws2_32 -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lversion -luuid -lcomdlg32 -lhid -lsetupapi")
	set(SDL2_DLL_IMPORTED_LOCATION "${SDL2_LIBDIR}/libSDL2.dll")
	set(SDL2_DLL_IMPORTED_IMBLIB "${SDL2_LIBDIR}/libSDL2.dll.a")
	#file(GLOB_RECURSE SDL2_LIBRARIES 	${CMAKE_CURRENT_LIST_DIR}/x86_64-w64-mingw32/lib/*.a)
endif ()

string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
message("SDL2 Libraries: " ${SDL2_LIBRARIES})

message("End sdl2-config.cmake")