message("Found sdl2_ttf-config.cmake at " ${CMAKE_CURRENT_LIST_DIR})

if(MSVC)
	message("Finding SDL_TTF for Visual C++")
	set(SDL2_TTF_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")
	# Support both 32 and 64 bit builds
	if (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	  message("64 Bit SDL_TTF Found")
	  set(SDL2_TTF_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2_ttf.lib")
	else ()
	  message("32 Bit SDL_TTF Found")
	  set(SDL2_TTF_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2_ttf.lib")
	endif ()
	
else ()
	message("Finding SDL_TTF for GCC/MinGW")
	set(SDL2_TTF_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/x86_64-w64-mingw32/include/SDL2")
	set(SDL2_TTF_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/x86_64-w64-mingw32/include/SDL2")
	set(SDL2_TTF_LIBDIR "${CMAKE_CURRENT_LIST_DIR}/x86_64-w64-mingw32/lib")
	set(SDL2_TTF_LIBRARIES "-L${SDL2_TTF_LIBDIR}  -lmingw32 -lSDL2main -lSDL2 -mwindows")
	SET(GCC_SDL2_TTF_COMPILER_FLAGS "-Wl,-Bstatic -lmingw32 -lSDL2main -lSDL2 -Wl,-Bdynamic -lws2_32 -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lversion -luuid -lcomdlg32 -lhid -lsetupapi")
	set(SDL2_TTF_DLL_IMPORTED_LOCATION "${SDL2_TTF_LIBDIR}/libSDL2_ttf.dll")
	set(SDL2_TTF_DLL_IMPORTED_IMBLIB "${SDL2_TTF_LIBDIR}/libSDL2_ttf.dll.a")
endif ()

string(STRIP "${SDL2_TTF_LIBRARIES}" SDL2_TTF_LIBRARIES)
message("SDL2_TTF Libraries: " ${SDL2_TTF_LIBRARIES})
message("SDL2_TTF Include Dirs: " ${SDL2_TTF_INCLUDE_DIRS})
message("End sdl2_ttf-config.cmake")